#!/bin/bash
TAG=${1:-}

if [ -z "$TAG" ]; then
    echo "Usage: $0 <version>"
    echo " Example: $0 0.0.1"
    exit 1
fi

echo "Building $TAG"
docker build -t machine-server-build -f Dockerfile.build .
docker run -ti --rm -e TAG -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/go/src/github.com/ehazlett/machine-server -w /go/src/github.com/ehazlett/machine-server machine-server-build make TAG=$TAG build image
